extends: "spectral:oas"

rules:
  operation-operationId:
    description: Each operation should have an operationId / 모든 Operation은 operationId를 가져야 합니다.
    message: "Missing operationId on {path}.{method}"
    severity: warn
    given: "$.paths[*][*]"
    then:
      field: operationId
      function: truthy
